name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Google Container Registry
      run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push backend image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest -f backend/Dockerfile .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest -f frontend/Dockerfile .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy to GKE (Optional)
      run: |
        kubectl set image deployment/backend backend=gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest
        kubectl set image deployment/frontend frontend=gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest

    - name: Deploy to Compute Engine or other services (Optional)
      run: |
        gcloud compute instances update-container backend-instance --container-image=gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest
        gcloud compute instances update-container frontend-instance --container-image=gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest
